-- ============================================================
-- MODULO 1: AUTENTICACION Y PERFILES
-- Base: Sakila migrada a PostgreSQL / Supabase
-- ============================================================

DROP TABLE IF EXISTS active_sessions CASCADE;
DROP TABLE IF EXISTS intrusion_events CASCADE;
DROP TABLE IF EXISTS login_audit CASCADE;
DROP TABLE IF EXISTS staff_auth CASCADE;
DROP TABLE IF EXISTS role_permissions CASCADE;
DROP TABLE IF EXISTS permissions CASCADE;
DROP TABLE IF EXISTS roles CASCADE;

CREATE TABLE roles (
    role_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name text NOT NULL UNIQUE,
    description text,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE permissions (
    permission_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_code text NOT NULL UNIQUE,
    description text
);

CREATE TABLE role_permissions (
    role_id integer NOT NULL REFERENCES roles(role_id) ON DELETE CASCADE,
    permission_id integer NOT NULL REFERENCES permissions(permission_id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE staff_auth (
    staff_id integer PRIMARY KEY REFERENCES staff(staff_id) ON DELETE CASCADE,
    role_id integer NOT NULL REFERENCES roles(role_id),
    password_hash text NOT NULL,
    must_change_password boolean NOT NULL DEFAULT false,
    failed_attempts integer NOT NULL DEFAULT 0,
    locked_until timestamp with time zone,
    last_login timestamp with time zone,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE login_audit (
    login_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id integer REFERENCES staff(staff_id) ON DELETE SET NULL,
    username text NOT NULL,
    ip_address text,
    user_agent text,
    success boolean NOT NULL,
    reason text,
    attempted_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE active_sessions (
    session_id text PRIMARY KEY,
    staff_id integer NOT NULL REFERENCES staff_auth(staff_id) ON DELETE CASCADE,
    ip_address text,
    user_agent text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    expires_at timestamp with time zone NOT NULL,
    is_revoked boolean NOT NULL DEFAULT false
);

CREATE INDEX idx_active_sessions_monitoring
ON active_sessions(expires_at, is_revoked);

CREATE TABLE intrusion_events (
    intrusion_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text,
    ip_address text,
    severity text NOT NULL DEFAULT 'MEDIUM',
    reason text NOT NULL,
    blocked_until timestamp with time zone,
    status text NOT NULL DEFAULT 'OPEN',
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

INSERT INTO roles (role_name, description)
VALUES
('ADMIN', 'Acceso total al sistema'),
('MANAGER', 'Gestion de tienda, personal e inventario local'),
('STAFF', 'Operaciones de caja, alquileres y devoluciones')
ON CONFLICT (role_name) DO NOTHING;

INSERT INTO permissions (permission_code, description)
VALUES
('AUTH_LOGIN', 'Puede iniciar sesion'),
('PROFILE_VIEW', 'Puede ver su perfil'),
('PROFILE_EDIT', 'Puede editar datos personales'),
('PASSWORD_CHANGE', 'Puede cambiar contraseña'),
('ROLE_MANAGE', 'Puede administrar roles'),
('SECURITY_AUDIT_VIEW', 'Puede ver auditoria de accesos'),
('INTRUDER_MONITOR', 'Puede monitorear intrusos')
ON CONFLICT (permission_code) DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM roles r
CROSS JOIN permissions p
WHERE r.role_name = 'ADMIN'
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM roles r
JOIN permissions p ON p.permission_code IN (
    'AUTH_LOGIN',
    'PROFILE_VIEW',
    'PROFILE_EDIT',
    'PASSWORD_CHANGE',
    'SECURITY_AUDIT_VIEW',
    'INTRUDER_MONITOR'
)
WHERE r.role_name = 'MANAGER'
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM roles r
JOIN permissions p ON p.permission_code IN (
    'AUTH_LOGIN',
    'PROFILE_VIEW',
    'PROFILE_EDIT',
    'PASSWORD_CHANGE'
)
WHERE r.role_name = 'STAFF'
ON CONFLICT DO NOTHING;

-- Crear Mara si no existe

INSERT INTO staff (
    first_name,
    last_name,
    address_id,
    email,
    store_id,
    active,
    username,
    password,
    last_update
)
SELECT
    'Mara',
    'Rivera',
    1,
    'admin@sakila.com',
    1,
    true,
    'mara.admin',
    'admin123',
    CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1
    FROM staff
    WHERE email = 'admin@sakila.com'
);

-- Crear Carlos si no existe

INSERT INTO staff (
    first_name,
    last_name,
    address_id,
    email,
    store_id,
    active,
    username,
    password,
    last_update
)
SELECT
    'Carlos',
    'Manager',
    1,
    'manager@sakila.com',
    1,
    true,
    'carlos.manager',
    'manager123',
    CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1
    FROM staff
    WHERE email = 'manager@sakila.com'
);

-- Autenticación ADMIN

INSERT INTO staff_auth (staff_id, role_id, password_hash, is_active)
SELECT s.staff_id, r.role_id, s.password, true
FROM staff s
JOIN roles r ON r.role_name = 'ADMIN'
WHERE s.email = 'admin@sakila.com'
ON CONFLICT (staff_id) DO NOTHING;

-- Autenticación MANAGER

INSERT INTO staff_auth (staff_id, role_id, password_hash, is_active)
SELECT s.staff_id, r.role_id, s.password, true
FROM staff s
JOIN roles r ON r.role_name = 'MANAGER'
WHERE s.email = 'manager@sakila.com'
ON CONFLICT (staff_id) DO NOTHING;

-- Autenticación STAFF para Mike y Jon

INSERT INTO staff_auth (staff_id, role_id, password_hash, is_active)
SELECT s.staff_id, r.role_id, '12345', true
FROM staff s
JOIN roles r ON r.role_name = 'STAFF'
WHERE s.email IN (
    'Mike.Hillyer@sakilastaff.com',
    'Jon.Stephens@sakilastaff.com'
)
ON CONFLICT (staff_id) DO NOTHING;

INSERT INTO login_audit (
    staff_id,
    username,
    ip_address,
    user_agent,
    success,
    reason
)
VALUES
(NULL, 'intruso@gmail.com', '190.50.10.2', 'Chrome', false, 'Usuario no autorizado'),
(NULL, 'admin@sakila.com', '192.168.1.20', 'Chrome', false, 'Contraseña incorrecta'),
(NULL, 'Mike.Hillyer@sakilastaff.com', '192.168.1.30', 'Chrome', false, 'Contraseña incorrecta');

INSERT INTO intrusion_events (
    username,
    ip_address,
    severity,
    reason,
    blocked_until,
    status
)
VALUES
('intruso@gmail.com', '190.50.10.2', 'HIGH', 'Usuario no autorizado', now() + interval '30 minutes', 'OPEN'),
('admin.fake@sakila.com', '190.20.5.10', 'MEDIUM', 'Demasiados intentos fallidos', now() + interval '15 minutes', 'OPEN');

CREATE OR REPLACE FUNCTION update_staff_auth_updated_at()
RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_staff_auth_updated_at ON staff_auth;

CREATE TRIGGER trg_staff_auth_updated_at
BEFORE UPDATE ON staff_auth
FOR EACH ROW
EXECUTE FUNCTION update_staff_auth_updated_at();